fuck you gh
Just-Some-Bots/MusicBot pull request #1494
Opened 2018-01-31 20:33 UTC by AutumnClove

Please make sure these boxes are checked (put an 'x' inside them) **before** creating the pull request.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### Description
I already did a pull request for this but I messed up the indent sizes and couldn't figure out how to fix it. 
So I just did a new one .-.

### Related issues (if applicable)
#1493

2018-02-05 23:40 UTC, jayktaylor requested changes

2018-02-05 23:40 UTC, jaydenkieran commented on musicbot/bot.py
> +        from sys import platform as _platform
bot.py already imports the sys module, you don't need to do this.

2018-02-05 23:40 UTC, jaydenkieran commented on musicbot/bot.py
> +            p = subprocess.Popen('runbot.bat', creationflags=subprocess.CREATE_NEW_CONSOLE)
This isn't how subprocesses work. You're just going to end up creating multiple processes within the same process, and then you'll eventually run into memory errors.

2018-02-05 23:40 UTC, jaydenkieran commented on musicbot/bot.py
> +        raise exceptions.TerminateSignal()
I don't think this point will ever actually be reached until the subprocesses have finished, which again is a problem that contributes to the memory issues mentioned beforehand.

2018-02-12 01:21 UTC, MattBSG requested changes
Subprocesses and threads are not a good solution because it can create huge problems especially pertaining to memory. It’s also really bad practice to make tens of sub-threads in cases a user may never actually close the bot. A completely different solution will be needed (think how ours is now, but add on to it)

2018-02-17 08:24 UTC, closed without merging