change id to user for more info.
Just-Some-Bots/MusicBot pull request #1517
Opened 2018-02-25 19:43 UTC by AutumnClove

Please make sure these boxes are checked (put an 'x' inside them) **before** creating the pull request.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### Description
ID is so boring why not provide some better info

### Related issues (if applicable)

2018-02-25 20:13 UTC, jaydenkieran commented
Please check why this failed a CI build and fix the issues.

2018-02-25 20:39 UTC, AutumnClove commented
@jaydenkieran 
Please help idk how to fix the indentation, githubs online editor confuses me inb4 use external, I did I copy pasted it over.

2018-02-25 21:11 UTC, jaydenkieran commented
You should use something like Visual Studio Code and update your repo the proper way.

2018-02-25 21:23 UTC, AutumnClove commented
I'm assuming the proper way is using github desktop? Just tried that and while the indentation is correct on my side, upon uploading it gets messed up =.=

2018-02-26 17:12 UTC, MattBSG commented
Just to add to this, the `id` command is currently depreciated.

2018-03-15 21:23 UTC, MattBSG requested changes

2018-03-15 21:23 UTC, MattBSG commented on musicbot/bot.py
> +        return Response(self.str.get('cmd-user', """
Please commit the updated `en.json` i18n file with the added string this references

2018-03-15 23:48 UTC, MattBSG approved these changes

2018-03-21 17:59 UTC, obi23lipnik approved these changes

2018-03-24 14:52 UTC, ImthePeach reviewed
This should have a embed availability as well for cleaner look, user info never looks good when it's not in an embed. Command should be called `info` or `userinfo` instead of `user` for sanity reasons. You aren't asking for what user is this, you are asking for info on the user.

2018-04-17 04:42 UTC, AutumnClove commented on musicbot/bot.py
> +            ph = message.content[stripped:]
ph stands for placeholder, not pornhub LUL

2018-11-20 01:21 UTC, AutumnClove commented
Holy crud it's been a year?

2019-05-25 05:16 UTC, closed without merging