Date and time logging plus a shutdown confirmation system
Just-Some-Bots/MusicBot pull request #1552
Opened 2018-03-23 07:09 UTC by OzoneHelix

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### Description
this will write logs with the time and date of when they are used as shown here 
![image](https://user-images.githubusercontent.com/29835364/37815847-04a1ecea-2e47-11e8-8636-b91ee2747f5d.png)
the logs will also delete after a days amount of secs   
in this pull request is an extension to the shutdown command
to prevent the bot from being shutdown by human error  
it confirms with the user that they want the bot to be shutdown
image example:
![image](https://user-images.githubusercontent.com/29835364/37815971-868d9952-2e47-11e8-8ca1-14b7095ca9a5.png)

### Related issues (if applicable)
of course the bot needs to be restarted to active log deletion

2018-03-23 07:10 UTC, OzoneHelix commented
forgive me I decided to redo my original pull request

2018-04-18 16:24 UTC, OzzyHelix commented
I made a mistake a while back  I had tried to go back to an earlier commit and it messed up the ability to merge

2018-04-18 17:27 UTC, OzoneHelix commented
ok I fixed most of the problems that arose from changes between updates

2018-04-30 01:33 UTC, MattBSG requested changes

2018-04-30 01:33 UTC, MattBSG commented on musicbot/bot.py
> +    async def cmd_shutdown(self, channel, message):
Can you please update to use discord.py rewrite syntax? https://discordpy.readthedocs.io/en/rewrite/migrating.html

2018-04-30 02:20 UTC, OzzyHelix commented
I wish to clarify the rewrite syntax is to use guild instead of server or is there more? the rewrite has me a bit confused I will continue working while I wait for an answer

2018-05-07 17:01 UTC, closed without merging

2018-06-06 13:24 UTC, Chaos21 commented on musicbot/bot.py
> +            await warning_message.add_reaction(r)
There's an attribute error at this line.

'Message' has no attribute 'add_reaction'