Repeat Functionality
Just-Some-Bots/MusicBot pull request #1677
Opened 2018-07-31 21:09 UTC by AleanaA

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### Description
Introduces Repeating queue functionality.
Current method to avoid errors, which could be done far better, is to check for data output from ffmpeg (No other method appeared viable as is, as there are any number of other errors outside the 404 error I used to test that could occur) and if data output is received, to turn off repeat. 
This means that the queue won't be lost, and the queue will begin to carry on as if repeat was turned off. If this occurs, users with permission to use the `repeat` command can easily turn it back on

### Related issues (if applicable)

Any repeat feature requests

2018-08-05 18:11 UTC, Chaos21 commented on musicbot/player.py
> +                    args=(self._current_player._player.source.original._process, self._stderr_future),
When runned, it seems that there's an error at this line

2018-08-05 18:14 UTC, AleanaA commented
Error being?

On Sun, Aug 5, 2018, 2:11 PM Chaos <notifications@github.com> wrote:

> *@Chaos21* commented on this pull request.
> ------------------------------
>
> In musicbot/player.py
> <https://github.com/Just-Some-Bots/MusicBot/pull/1677#discussion_r207744441>
> :
>
> > @@ -304,6 +315,14 @@ def play(self, _continue=False):
>
>                  stderr_thread.start()
>
> +                reperrcatch = Thread(
> +                    target=self.repeat_err,
> +                    args=(self._current_player._player.source.original._process, self._stderr_future),
>
> When runned, it seems that there's an error at this line
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Just-Some-Bots/MusicBot/pull/1677#pullrequestreview-143418878>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIL6m5J4MJagB_NRlthIQ7yj-BvR8YA5ks5uNzVugaJpZM4Vpae2>
> .
>

2018-08-06 05:48 UTC, Chaos21 commented
@AleanaA 
![image](https://user-images.githubusercontent.com/39013902/43698959-e8962036-994c-11e8-8a5d-4c5b5ead1bf1.png)

Here's the error I've got. I've placed correctly the modifications, I've even removed them and tried again, and again.

2018-08-06 05:55 UTC, AleanaA commented
Can I have more information? What commands were run prior, what commands
were run after, are you on the review branch, etc.

On Mon, Aug 6, 2018, 1:48 AM Chaos <notifications@github.com> wrote:

> @AleanaA <https://github.com/AleanaA>
> [image: image]
> <https://user-images.githubusercontent.com/39013902/43698959-e8962036-994c-11e8-8a5d-4c5b5ead1bf1.png>
>
> Here's the error I've got. I've placed correctly the modifications, I've
> even removed them and tried again, and again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Just-Some-Bots/MusicBot/pull/1677#issuecomment-410595698>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIL6m2DPVcLVt3nCtpk1Kfo8Cb48a8Chks5uN9iagaJpZM4Vpae2>
> .
>

2018-08-09 14:37 UTC, Chaos21 commented
@AleanaA Of course.
I've tested it many times.
So. When running, the bot isn't able to play music. All his commands work like he can join the voice channel, etc, but it's like the bot is in 'pause'. the current music is like not played as all. The green circle around the avatar don't appear.
I'm on the 1.9.7 version.

2018-08-09 14:39 UTC, Chaos21 commented
I don't know if when you're running the program, you'll get the same error. As well, it's what I've got.

2018-08-09 14:58 UTC, AleanaA commented
All pull requests target review. Review uses d.py rewrite, and no pull
requests should be compatible with the master brach until the two get
merged. Please use review if you want this functionality to work.

On Thu, Aug 9, 2018, 10:39 AM Chaos <notifications@github.com> wrote:

> I don't know if when you're running the program, you'll get the same
> error. As well, it's what I've got.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Just-Some-Bots/MusicBot/pull/1677#issuecomment-411781001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIL6m8H1UcI-4YIoXvgr8IDbEDYwYsOUks5uPEmJgaJpZM4Vpae2>
> .
>

2019-03-02 00:21 UTC, maquikun approved these changes
Works for me on the latest version of the bot, Got some unexpected indentation errors at first but fixed them buy copying and pasting lines 318 and 328.

2019-03-06 02:41 UTC, YuiyuD commented
@AleanaA I got this error when using skip in list queue, seems, your repeat only repeat 1 song, in the list they will skip all
https://cdn.discordapp.com/attachments/549474261878964229/552680564688289803/unknown.png

2019-08-25 20:53 UTC, jayktaylor requested changes
Can you ensure this works against the latest code in review?

2019-08-25 20:53 UTC, jaydenkieran commented on musicbot/bot.py
> +            return Response('Repeat disabled!', delete_after=10)
Ternary op probably better here

2019-08-25 20:53 UTC, jaydenkieran commented on musicbot/bot.py
> +            lines.append("Repeat mode is **off**")
Another place for a ternary op

2020-04-20 01:34 UTC, AleanaA commented
Unmaintained, rewrite of this PR planned.

2020-04-20 01:34 UTC, closed without merging