Adds an option to dm help
Just-Some-Bots/MusicBot pull request #1856
Opened 2019-03-19 17:26 UTC by AutumnClove

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### Description
Adds an option to send the help menu directly to the user who called it. 
Useful for spam prevention.

### Related issues (if applicable)

2019-04-19 10:46 UTC, jayktaylor requested changes

2019-04-19 10:46 UTC, jaydenkieran commented on musicbot/bot.py
> +            log.info("  Direct message help: " + ['Disabled', 'Enabled'][self.config.leavenonowners])
Should not be `self.config.leavenonowners`

2019-04-19 10:46 UTC, jaydenkieran commented on musicbot/bot.py
> +            await self.safe_send_message(message.author, desc, expire_in=60)
It feels like we still should give acknowledgement in the user's channel that we've DM'd them?

2019-05-01 00:16 UTC, jayktaylor submitted a review, later dismissed

2019-05-01 00:16 UTC, jaydenkieran commented on musicbot/bot.py
> +            return Response(":mailbox_with_mail:", reply=False, expire_in=15)
Shouldn't this be `delete_after`?

2021-08-20 11:40 UTC, AutumnClove reviewed
Pls approve

2021-08-29 09:58 UTC, AutumnClove commented
Closing because https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1

2021-08-29 09:58 UTC, closed without merging