Merge pull request #40 from Just-Some-Bots/review
Just-Some-Bots/MusicBot pull request #1927
Opened 2019-07-17 03:40 UTC by AutumnClove

Review

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5.3 or higher

----

### Description
Adds a check to ignore other bots with an id override

### Related issues (if applicable)

2019-07-17 04:10 UTC, TheerapakG requested changes

2019-07-17 04:10 UTC, TheerapakG commented on musicbot/config.py
> +        self.bot_exception_ids = config.get("Permissions", "BotExceptionIDs", fallback=ConfigDefaults.bot_exception_ids)
You need to process ids after this as this will get str, not set of ints. Preferably process it in run_checks

2019-07-17 04:10 UTC, TheerapakG commented on musicbot/bot.py
> +        if message.author == message.author.bot and message.author.id is not self.config.bot_exception_ids:
You forgot in
`message.author.id is not in self.config.bot_exception_ids:`

2019-07-17 04:27 UTC, TheerapakG approved these changes

2019-07-23 13:02 UTC, jayktaylor approved these changes

2019-07-23 13:03 UTC, merged