Installation page for OpenBSD
Just-Some-Bots/MusicBot pull request #2001
Opened 2019-12-12 07:30 UTC by williewillus

### Description
Without too much effort, I got the bot set up on OpenBSD 6.6, so here's a guide for future users wanting to do the same.

2020-03-09 22:37 UTC, AleanaA commented
Hi there!
As to keep down on clutter of the main repo's wiki, unofficial/unsupported guides have been continued to be made on an unofficial wiki page. This can be found here: https://aleanaazure.xyz/doku.php?id=musicbot
With permission, I'd like to incorporate this guide into the unofficial wiki until either @jaydenkieran or @srhinos provide information as to whether this should be put into the official wiki pages.

2020-03-10 01:49 UTC, williewillus commented
You have my permission to copy this PR's contents into the unofficial wiki

2020-03-14 11:37 UTC, amit177 requested changes

2020-03-14 11:37 UTC, AmiT177 commented on _docs/installing/openbsd.md
> +WARNING: If you have the py3-PyNaCl package installed, the final command will overwrite your system pynacl, which is likely newer, with pynacl 1.2.1, potentially breaking other packages. This can be
Could you move this warning above the command?
That way we can ensure people will read it instead of pasting the command and then reading.

2020-03-14 12:15 UTC, AmiT177 commented
Tested and it installs fine, just that comment is what I'm worried about.
Once that's changed, can be merged.

2020-03-14 20:05 UTC, williewillus commented
done

2020-03-14 20:59 UTC, amit177 approved these changes

2020-03-14 21:21 UTC, AmiT177 commented
Could you try making a new PR? for some reason travis won't let me merge it

2020-03-14 22:56 UTC, closed without merging

2020-03-14 22:57 UTC, williewillus commented
#2026 should have another copy