Auto summon when 'play' is used
Just-Some-Bots/MusicBot pull request #2024
Opened 2020-03-14 09:50 UTC by AmiT177

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5.3 or higher

----

### Description

New feature: auto summon when !play is used

### Related issues (if applicable)

#837

2020-03-25 17:15 UTC, TheManchineel commented
This seems to work very well and makes for a great quality of life improvement with the bot. When is this going to be merged?

2020-03-25 17:29 UTC, AmiT177 commented
It works, but the code itself is not great.

2020-03-25 17:36 UTC, TheManchineel commented
@AmiT177 I see, I'm no developer so I didn't consider that aspect :P

2020-04-11 04:20 UTC, InfectedMagic approved these changes
this code works great, and tho the code is not the greatest it works and makes the bot a bit more like other music like Rythm where you type !play or !p and it auto joins the channel you are in and starts playing your song.

2020-04-23 12:22 UTC, jayktaylor requested changes

2020-04-23 12:22 UTC, jaydenkieran commented on musicbot/bot.py
> +                    if message.author.id == self.config.owner_id or (user_permissions.command_whitelist and command in user_permissions.command_whitelist and user_permissions.command_blacklist and co
The same if statements are further down in the code here:

```py
            if message.author.id != self.config.owner_id:
                if user_permissions.command_whitelist and command not in user_permissions.command_whitelist:
                    raise exceptions.PermissionsError(
                        "This command is not enabled for your group ({}).".format(user_permissions.name),
                        expire_in=20)
                elif user_permissions.command_blacklist and command in user_permissions.command_blacklist:
                    raise exceptions.PermissionsError(
                        "This command is disabled for your group ({}).".format(user_permissions.name),
                        expire_in=20)
```

...so I'd probably recommend splitting that out to its own function and calling the function instead.

2020-05-31 16:17 UTC, LegalSmeagol commented
Using play to summon the bot works for me, but other users in my Discord are receiving the "bot is not in a voice channel" error. What is it I'm missing?

2021-03-25 21:22 UTC, closed without merging