created pl.json, edited en.json and bot.py
Just-Some-Bots/MusicBot pull request #2165
Opened 2020-11-06 16:20 UTC by MrWurste

1. Translated commads strings to polish (pl.json).
2. Edited bot.py to give possibility to translate bot's song play messages (async def on_player_play method):
+ skip message when queuer is not in voice,
+ mention to queuer when mentrions are anabled,
+ default 'now plaing in' message,
+ message when autoplalist or autoqueue song is played.
3. Edited en.json to add string lines mentioned above.
4. Translated en.json's new lines in pl.json.

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5.3 or higher

----

### Description
Translation of all command strings from en.json file to polish (pl.json) and new messages lines exported from bot.py to en.json with polish translation.
Absence of new lines in another language files doesn't couse eny errors. Default english messages are used.

### Related issues (if applicable)

2020-11-06 21:54 UTC, srhinos approved these changes
Big fan of these changes! Thanks for the contribution

2021-01-22 08:01 UTC, AutumnClove requested changes

2021-01-22 08:01 UTC, AutumnClove commented on config/i18n/pl.json
> +	"on_player_play-onChannel_plaingMention":"{author} - Twój utwór {title} jest teraz odtwarzany w {channel}!",
plaingMention -> playingMention
Keep it in line with the rest

2021-01-22 12:20 UTC, MrWurste commented
Ok, I'll change it, sorry for mistake.

pt., 22 sty 2021, 09:01 użytkownik Winter <notifications@github.com>
napisał:

> *@AutumnClove* requested changes on this pull request.
> ------------------------------
>
> In config/i18n/pl.json
> <https://github.com/Just-Some-Bots/MusicBot/pull/2165#discussion_r562448681>
> :
>
> > +    "cmd-option-invalid-param": "Podane parametry są nieprawidłowe.",
>
> +    "cmd-queue-more": "\n... i %s więcej",
>
> +    "cmd-queue-none": "Nie ma zakolejkowanych utworów! Dodaj coś przy użyciu {}play.",
>
> +    "cmd-queue-playing-author": "Aktualnie odtwarzane: `{0}`, dodane przez `{1}` {2}\n",
>
> +    "cmd-queue-playing-noauthor": "Aktualnie odtwarzane: `{0}` {1}\n",
>
> +    "cmd-queue-entry-author": "{0} -- `{1}` przez `{2}`",
>
> +    "cmd-queue-entry-noauthor": "{0} -- `{1}`",
>
> +    "cmd-clean-invalid": "Nieprawidłowy parametr. Proszę podać ilość wiadomości do wyszukania.",
>
> +    "cmd-clean-reply": "Wyczyszczono {0} wiadomości{1}.",
>
> +    "playlists-noperms": "Nie masz uprawnień do podania listy odtwarzania",
>
> +    "playlists-big": "Lista odtwarzania ma za dużo pozycji ({0} > {1})",
>
> +    "playlists-limit": "Pozycje w liście odtwarzania + zakolejkowane przez Ciebie uwory osiągnęły limit ({0} + {1} > {2})",
>
> +    "karaoke-enabled": "Tryb karaoke jest włączony, proszę spróbować ponownie, gdy będzie wyłączony!",
>
> +    "left-no-owner-guilds": "Opuszczono `{}`, ponieważ właściciel bota nie został tam odnaleziony.",
>
> +	"on_player_play-onChannel_authorNotInChannel_skipWhenAbsent":"Pomijanie następnego utworu {channel}: {title} dodanego przez {author}, gdyż dodającego/dodającej nie ma na kanale!",
>
> +	"on_player_play-onChannel_plaingMention":"{author} - Twój utwór {title} jest teraz odtwarzany w {channel}!",
>
>
> plaingMention -> playingMention
> Keep it in line with the rest
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Just-Some-Bots/MusicBot/pull/2165#pullrequestreview-574022407>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARKT6MGL32QK5HSFJVKQIK3S3EWGNANCNFSM4TM33JBQ>
> .
>

2021-02-09 15:00 UTC, jayktaylor submitted a review, later dismissed

2021-02-09 15:00 UTC, jaydenkieran commented on musicbot/bot.py
> +                newmsg = self.str.get('on_player_play-onChannel_plaingMention', "{author} - your song {title} is now playing in {channel}!").format (
Fix `plaingMention` to `playingMention`

2021-02-09 15:00 UTC, jaydenkieran commented on musicbot/bot.py
> +            newmsg = self.str.get ('on_player_play-onChannel_noAuthor_autoplalist', "Now playing automatically added entry {title} in {channel}!").format (
`autoplalist` -> `autoPlaylist`

2021-06-19 05:34 UTC, AutumnClove approved these changes

2021-06-19 05:38 UTC, AutumnClove commented
@MrWurste could you take a glance over the merge I did with review and make sure everything looks okay? I did that at like 2am after an 11 hour work shift lol. Trying to update some PR's and hopefully merge soon and want to see these improvements in the bot.

2021-08-20 11:01 UTC, AutumnClove approved these changes
Love it

2021-08-20 11:02 UTC, AutumnClove approved these changes

2021-08-20 18:23 UTC, merged