Feature changes
Just-Some-Bots/MusicBot pull request #671
Opened 2016-10-17 12:19 UTC by KingGold171

Added - MaxVolume in permissions (Limit how loud people can set the bots
volume, the number set in the permissions.ini is the limit)

Changed - Volume to display current volume only

Added - SetVolume to set the volume of the bot (works exact same as
volume did.

2016-10-18 02:43 UTC, KingGold171 commented
People on the main server i run the music bot on wanted the ability to check current volume.  But due to the volume being a single permissions node which gives access to check and set,   This has been split into two permissions nodes.   One  for checking, and one for setting.

2016-10-23 22:44 UTC, jaydenkieran commented
Please can you direct changes to the `review` branch.

2016-10-25 22:00 UTC, jayktaylor requested changes

2016-10-25 22:00 UTC, jaydenkieran commented on musicbot/bot.py
> +    async def cmd_setvolume(self, message, player, permissions, new_volume=None):
This shouldn't be it's own command. For efficiency, it should be a part of the `volume` command, like it has always been.

2016-10-25 22:00 UTC, jaydenkieran commented on musicbot/bot.py
> +                "[ERROR] You are not able to set the volume above (%s)" % permissions.max_volume
Probably remove the `[ERROR]` here, it already says `You do not have permission to use this command.` because of the exception that you're raising.

2016-10-25 22:00 UTC, jaydenkieran commented on musicbot/permissions.py
> +        self.max_volume = section_data.get ('MaxVolume', fallback=PermissionsDefaults.MaxVolume)
Remove the space after `section_data.get`

2016-10-25 23:12 UTC, KingGold171 commented on musicbot/bot.py
> +                "[ERROR] You are not able to set the volume above (%s)" % permissions.max_volume
What if i was to have the [Error]    is they have permissions to change it but try going above the set limit, and the default if they don't ?

2016-10-25 23:37 UTC, KingGold171 commented on musicbot/bot.py
> +    async def cmd_setvolume(self, message, player, permissions, new_volume=None):
Volume and Setvolume back as one command (MaxVolume permissions still included)

2016-10-25 23:37 UTC, KingGold171 commented on musicbot/permissions.py
> +        self.max_volume = section_data.get ('MaxVolume', fallback=PermissionsDefaults.MaxVolume)
Space removed

2016-10-25 23:48 UTC, KingGold171 commented on musicbot/bot.py
> +                "[ERROR] You are not able to set the volume above (%s)" % permissions.max_volume
Bot.py changes based on Atom -- @jaydenkieran

2016-10-25 23:54 UTC, KingGold171 commented
Alot of changes based on Atom 👍 Doesn't seem to break anything  @jaydenkieran

2017-01-25 06:47 UTC, KingGold171 commented
Redone using the review branch as a base [CLOSED]

2017-01-25 06:47 UTC, closed without merging